FROM python:3.10.12-slim

RUN groupadd -g 1000 python && \
    useradd -r -u 1000 -g python python

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir /app && chown python:python /app
WORKDIR /app

COPY . .

USER 1000

CMD ["python", "main.py"]
